import fs from 'node:fs';import path from 'node:path';
const exts=new Set(['.js','.mjs','.cjs','.ts','.tsx','.jsx','.html','.json','.yml','.yaml','.toml','.env']);const skip=new Set(['node_modules','.git','dist','build','.next','coverage','.visual-work']);
function walk(root,out=[]){for(const e of fs.readdirSync(root,{withFileTypes:true})){if(skip.has(e.name))continue;const p=path.join(root,e.name);if(e.isDirectory())walk(p,out);else if(exts.has(path.extname(e.name))||e.name.startsWith('.env'))out.push(p)}return out}
function first(text,re){const ls=text.split(/\r?\n/);for(let i=0;i<ls.length;i++)if(re.test(ls[i]))return{line:i+1,snippet:ls.slice(Math.max(0,i-1),i+2).map((x,n)=>`${Math.max(1,i)}+${n}: ${x.trim()}`).join('\n').slice(0,650)};return{}}
export function runSecurityAudit(root){const out=[];for(const file of walk(root)){let text='';try{text=fs.readFileSync(file,'utf8')}catch{continue}const rel=path.relative(root,file);const add=(sev,bot,rule,re,msg,rec,conf=80,cat='Assinatura/Sessão')=>{const e=first(text,re);out.push({severity:sev,bot,rule,file:rel,line:e.line||null,snippet:e.snippet||'',message:msg,recommendation:rec,confidence:conf,category:cat})};
if(/(?:api[_-]?key|secret|token|password)\s*[:=]\s*['"][A-Za-z0-9_\-.]{16,}['"]/i.test(text))add('critical','SecretBot','POSSIBLE_HARDCODED_SECRET',/(?:api[_-]?key|secret|token|password)\s*[:=]/i,'Possível credencial/token fixo no código cliente ou repositório.','Remova o segredo do código, rotacione-o e use variável secreta no servidor.',94,'Segredos');
if(/authorized\s*[:=]\s*true|status\s*[:=]\s*['"]AUTHORIZED['"]/i.test(text)&&!/sessionToken|licenseSession|signature|verify/i.test(text))add('high','LicenseGateBot','CLIENT_ONLY_AUTHORIZATION',/authorized\s*[:=]\s*true|status\s*[:=]\s*['"]AUTHORIZED['"]/i,'Autorização aparenta depender de estado do cliente sem evidência próxima de sessão assinada.','Exija validação server-side e credencial assinada antes de liberar recursos.',88);
if(/sessionToken|licenseSession/i.test(text)&&!/expir|expires|\bexp\b|ttl/i.test(text))add('medium','SessionBot','SESSION_EXPIRY_NOT_EVIDENT',/sessionToken|licenseSession/i,'Uso de sessão detectado sem expiração evidente no mesmo arquivo.','Confirme expiração curta e rejeição server-side de sessão vencida.',72);
if(/deviceId/i.test(text)&&!/device_mismatch|deviceMismatch|timingSafeEqual|verify/i.test(text))add('medium','DeviceBot','DEVICE_BINDING_NOT_EVIDENT',/deviceId/i,'Device ID é usado, mas o vínculo criptográfico/validação não é evidente neste arquivo.','Valide deviceId no servidor contra o valor assinado na sessão.',70);
if(/localStorage\.(?:setItem|getItem)\([^\n]*(?:token|license|session)/i.test(text))add('high','StorageBot','SENSITIVE_SESSION_LOCALSTORAGE',/localStorage\.(?:setItem|getItem)/i,'Possível sessão/licença persistida em localStorage, acessível a JavaScript da origem.','Evite persistir token sensível; reduza TTL e superfície de XSS.',90,'Armazenamento');
if(/WebSocket\(|new WebSocket/i.test(text)&&!/wss:\/\//i.test(text))add('high','TransportBot','WEBSOCKET_TLS_NOT_EVIDENT',/(?:new\s+)?WebSocket\(/i,'WebSocket detectado sem wss:// evidente no arquivo.','Garanta transporte WSS em produção.',68,'Transporte');
if(/\.execute\s*=|window\.[A-Za-z0-9_$]+\s*=|globalThis\.[A-Za-z0-9_$]+\s*=/i.test(text)&&/(command|execute|bridge|game)/i.test(text))add('medium','ExposureBot','PUBLIC_RUNTIME_CAPABILITY',/\.execute\s*=|window\.[A-Za-z0-9_$]+\s*=|globalThis\.[A-Za-z0-9_$]+\s*=/i,'Capability/API operacional pode estar exposta globalmente no runtime.','Exponha somente fachada mínima e proteja operações sensíveis com sessão validada.',76,'Superfície pública');
if(/fetch\([^\n]+licenses?\/validate|\/api\/licenses\/validate/i.test(text))add('low','LicenseFlowBot','LICENSE_VALIDATION_ENDPOINT',/licenses?\/validate|\/api\/licenses\/validate/i,'Fluxo de validação de licença localizado para revisão.','Confirme rate limit, respostas genéricas e emissão de sessão somente após autorização.',92);
if(/429|TOO_MANY_ATTEMPTS|rate.?limit|brute.?force/i.test(text))add('info','RateLimitBot','ANTI_BRUTEFORCE_PRESENT',/429|TOO_MANY_ATTEMPTS|rate.?limit|brute.?force/i,'Sinais de tratamento anti-bruteforce/rate limit encontrados.','Mantenha o controle no servidor e registre tentativas anômalas.',85,'Proteção');
}return out}
