import fs from 'node:fs';
import path from 'node:path';

const exts=new Set(['.html','.css','.js','.jsx','.ts','.tsx','.vue','.svelte']);
const skip=new Set(['node_modules','.git','dist','build','.next','coverage','.visual-work']);
function files(root,out=[]){for(const e of fs.readdirSync(root,{withFileTypes:true})){if(skip.has(e.name))continue;const p=path.join(root,e.name);if(e.isDirectory())files(p,out);else if(exts.has(path.extname(e.name)))out.push(p)}return out}
function evidence(text,re){const lines=text.split(/\r?\n/);for(let i=0;i<lines.length;i++){re.lastIndex=0;if(re.test(lines[i])){const start=Math.max(0,i-1),end=Math.min(lines.length,i+2);return{line:i+1,snippet:lines.slice(start,end).map((x,n)=>`${start+n+1}: ${x.trim()}`).join('\n').slice(0,650)}}}return null}
export function runStaticAudit(root){const findings=[],seen=new Set();for(const file of files(root)){const text=fs.readFileSync(file,'utf8'),rel=path.relative(root,file),ext=path.extname(file);const add=(severity,bot,rule,re,message,recommendation,confidence=75,category='Visual',evidenceLevel='suspeita')=>{const key=`${rel}|${rule}`;if(seen.has(key))return;seen.add(key);const ev=evidence(text,re)||{};findings.push({severity,bot,rule,file:rel,line:ev.line||null,snippet:ev.snippet||'',confidence,category,message,recommendation,evidenceLevel})};
// Estado .active em CSS, sozinho, não prova bug. Só sinalizamos quando JS adiciona estado sem limpeza evidente.
if(/\.[jt]sx?$/.test(ext)&&/classList\.add\(['"](?:active|selected)/i.test(text)&&!/classList\.(?:remove|toggle)\(['"](?:active|selected)|classList\.forEach|querySelectorAll[^\n]{0,160}classList\.remove/i.test(text))add('medium','StateBot','POSSIBLE_STICKY_SELECTED_STATE',/classList\.add\(['"](?:active|selected)/i,'Código adiciona estado selecionado sem limpeza evidente no mesmo módulo.','Revise o fluxo completo; confirme o bug dinamicamente antes de alterar.',76,'Estado/Interação','forte');
if(/:hover/.test(text)&&!/@media\s*\([^)]*hover\s*:\s*hover/i.test(text))add('low','TouchBot','UNGUARDED_HOVER',/:hover/,'Existe :hover sem proteção de capacidade; é uma compatibilidade potencial, não bug confirmado.','Considere @media (hover:hover) and (pointer:fine) quando o hover alterar estado importante.',68,'Touch/iOS');
if(/position\s*:\s*fixed/i.test(text)&&!/safe-area-inset|100dvh|dvh/i.test(text))add('low','ViewportBot','FIXED_IOS_VIEWPORT',/position\s*:\s*fixed/i,'Elemento fixed sem tratamento de safe-area/dvh detectado; valide apenas se ocupar viewport/tela cheia.','Teste em Safari/iOS antes de alterar.',62,'Responsividade');
if(/100vh/.test(text))add('medium','ViewportBot','LEGACY_100VH',/100vh/,'100vh pode gerar corte ou salto com barras do Safari móvel.','Use fallback/100dvh quando o elemento depender da altura visível.',85,'Responsividade','forte');
if(/outline\s*:\s*(?:none|0)/i.test(text)&&!/:focus-visible/i.test(text))add('medium','FocusBot','FOCUS_REMOVED',/outline\s*:\s*(?:none|0)/i,'Indicação de foco removida sem focus-visible detectado.','Adicione um estado :focus-visible perceptível.',82,'Acessibilidade/Estado','forte');
if(/touchstart|pointerdown/i.test(text)&&!/touchend|pointerup|pointercancel/i.test(text))add('medium','TouchBot','INCOMPLETE_POINTER_LIFECYCLE',/touchstart|pointerdown/i,'Início de interação pointer/touch sem finalização evidente neste módulo.','Verifique handlers importados/globais antes de corrigir.',78,'Touch/iOS','forte');
if(/overflow\s*:\s*hidden/i.test(text))add('info','LayoutBot','OVERFLOW_HIDDEN',/overflow\s*:\s*hidden/i,'overflow:hidden encontrado. É informativo: frequentemente é intencional.','Só altere se teste de viewport confirmar conteúdo cortado.',45,'Layout');
if(/z-index\s*:\s*\d{4,}/i.test(text))add('info','LayerBot','EXTREME_Z_INDEX',/z-index\s*:\s*\d{4,}/i,'z-index alto encontrado; pode ser intencional em gates/modais.','Revise somente se houver disputa real de camadas.',42,'Camadas');
if(/min-width\s*:\s*(?:[5-9]\d\d|\d{4,})px/i.test(text))add('medium','ResponsiveBot','LARGE_MIN_WIDTH',/min-width\s*:\s*(?:[5-9]\d\d|\d{4,})px/i,'min-width grande pode causar overflow horizontal.','Valide nos viewports suportados.',80,'Responsividade','forte');
if(/font-size\s*:\s*(?:[0-8])px/i.test(text))add('low','ReadabilityBot','TINY_TEXT',/font-size\s*:\s*(?:[0-8])px/i,'Texto de 8px ou menos detectado; pode prejudicar leitura.','Confirme se é texto informativo e revise a escala tipográfica.',68,'Legibilidade');
}return findings}
